/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.30.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { makeFunctionReference } from "convex/server";

export const api = {
  users: {
    currentUser: makeFunctionReference("users:currentUser"),
  },
};
export const internal = {};
