/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.30.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { FunctionReference } from "convex/server";

/**
 * A type describing your app's public Convex API.
 */
export declare const api: {
  users: {
    currentUser: FunctionReference<"query", "public", {}, any>;
  };
};
export declare const internal: any;
