/* eslint-disable */
/**
 * Generated server utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.30.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { queryGeneric, mutationGeneric, actionGeneric } from "convex/server";

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const action = actionGeneric;
export const internalQuery = queryGeneric;
export const internalMutation = mutationGeneric;
export const internalAction = actionGeneric;
