/* eslint-disable */
/**
 * Generated server utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.30.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import {
  ActionCtx as GenericActionCtx,
  MutationCtx as GenericMutationCtx,
  QueryCtx as GenericQueryCtx,
} from "convex/server";
import { DataModel } from "./dataModel.js";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const query: any;
export declare const mutation: any;
export declare const action: any;
export declare const internalQuery: any;
export declare const internalMutation: any;
export declare const internalAction: any;
